### ---Test the SERVER 
GET http://localhost:8080

### --Test ALL WZ Meta Weapons
GET http://localhost:8080/wzmeta

### --Test SINGLE WZ Meta Weapon
GET http://localhost:8080/wzmeta/67042e0d3ff6863a1b20f07e

### ---Render ALL WZ Meta Weapons---
GET https://creestian.onrender.com/wzmeta

### ---Render SINGLE WZ Meta Weapon
GET https://creestian.onrender.com/wzmeta/67042e0d3ff6863a1b20f07e

### ---Create a WZ Meta Weapon---
POST http://localhost:8080/wzmeta HTTP/1.1
Content-Type: application/json

{
  "name": "PULEMYOT 762",
  "muzzle": "QUARTERMASTER SUPPRESSOR",
  "barrel": "ST PYRO HEAVY BARREL",
  "optic": "SZ HOLOTHERM",
  "stock": "IVANOV WOOD STOCK",
  "magazine": "",
  "underbarrel": "",
  "ammunition": "7.62X54MMR HIGH VELOCITY",
  "rearGrip": ""
}

### Update a WZ Meta Weapon
PUT http://localhost:8080/wzmeta/6704414f822a6af86ace125a HTTP/1.1
Content-Type: application/json

{
  "name": "PULEMYOT 762",
  "muzzle": "QUARTERMASTER SUPPRESSOR",
  "barrel": "ST PYRO HEAVY BARREL",
  "optic": "SZ HOLOTHERM",
  "stock": "IVANOV WOOD STOCK",
  "magazine": "NA",
  "underbarrel": "NA",
  "ammunition": "7.62X54MMR HIGH VELOCITY",
  "rearGrip": "NA"
}

### Delete a WZ Meta Weapon
DELETE http://localhost:8080/wzmeta/6704414f822a6af86ace125a HTTP/1.1